spring.application.name=ItemViewer

##port setting
#server.port=8081

#database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/microvolts_items
spring.datasource.username=postgres
spring.datasource.password=0813459596

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#app settings
